"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const projects_controllers_1 = require("../controllers/projects.controllers");
const router = (0, express_1.Router)();
router.get('/projects', projects_controllers_1.getProjects);
router.post('/projects', (req, res) => { res.send("ff"); });
router.get('/projects/:id');
router.put('/projects/:id', projects_controllers_1.updateProject);
router.delete('projects/:id', projects_controllers_1.deleteProject);
exports.default = router;
